config/routes.rb
Rails.application.routes.draw do
  root 'urls#index'
  resources :urls 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
	validates :long_url, presence: true 
	validate :http
	before_create:shorten 

	def shorten
		self.short_url = SecureRandom.hex(5)
	end 

	def http 
		if self.long_url[0..3] != 'http' && self.long_url[0..2] == 'www'
			self.long_url = 'http://' + self.long_url 
		elsif self.long_url[0..2] != 'www' && self.long_url[0..3] != 'http'
			self.long_url = 'http://www.' + self.long_url 
		elsif self.long_url[0..3] == 'http'

		end 
	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

	def index
		@urls = Url.all 
	end 

	def show 
		byebug
		@urls = Url.find(params[:id])
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_for @url do |f| %>
  <p>
    <%= f.label "Type your URL here:" %><br>
    <%= f.text_field :long_url %>
  </p>

  <p>
    <%= f.submit "Shorten URL!" %>
  </p>
    <% end %>

app/views/urls/index.html.erb
<table>
<tr>
<th>Original URL</th>
<th>Shortened URL</th>
</tr>

<%  @urls.each do |url| %>
    <tr>
    <td> <%= link_to url.long_url, url_path(url.id) %></td>
    <td> <%= url.short_url %></td>
    </tr>   
<% end %>
</table>

app/views/urls/show.html.erb
<h3>This is urls/show</h3>
    <p><%= @urls.long_url %></p>
    <p><%= @urls.short_url %></p>
    <%= link_to 'Back', urls_path %>